#!/bin/bash

# vim:tw=80:tabstop=2:shiftwidth=2

# Copyright (c) 2012-present, Phil Dibowitz <phil@ipom.com>
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#  * Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#  * Redistributions in
#    binary form must reproduce the above copyright notice, this list of
#    conditions and the following disclaimer in the documentation and/or other
#    materials provided with the distribution.
#  * Neither the name of the author nor the names of its contributors may be
#    used to endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

#
# You can find the latest version of this at:
#   https://github.com/jaymzh/v6-gw-scripts
#
# Debian-style if-up.d script for firing off dhclient for ipv6
#

# Change EXT_IFACE by updating the config file
CONF='/etc/ipv6_prefix_dhclient.conf'
EXT_IFACE='eth0'
PIDFILE="/var/run/dhclient6.$IFACE.pid"
LEASEFILE="/var/lib/dhcp/dhclient6.$IFACE.leases"

[ -r $CONF ] && . $CONF

# We only care about the external interface.
if [ "$IFACE" != "$EXT_IFACE" ]; then
    logger -t 99-ipv6 "Called with $IFACE, skipping"
    exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
    logger -t 99-ipv6 "Called with mode $MODE, skipping"
    exit 0
fi

logger -t 99-ipv6 "Configuring $IFACE for v6..."

# If there's a stale dhclient, kill it
if [ -s "$PIDFILE" ]; then
    kill $(cat $PIDFILE) &>/dev/null
fi

# Start our new one
cmd="/sbin/dhclient -6 -P -pf $PIDFILE -lf $LEASEFILE -v $IFACE"

# We have to start it in a sub-shell later, it dies if we start it
# directly from here for some reason.
( ( sleep 5; $cmd ) & ) &

# reload firewall rules
/etc/network/ip6tables reload

exit 0
